### PR TITLE
Add support for react-native > 0.26+

### LINKED ISSUE #4: Android not functioning in rn 26
I have been using this component for months on ios.  Today I tried it on android and it will not open a modal.  It works on iOS still but not on android

### PR DESCRIPTION
**Pull request by jpgarcia**
It will fixes #4

### CODE REVIEW

**Comment by httnn** [comment]
this probably breaks RN versions before 0.26?

**Comment by jpgarcia** [comment]
No it does not. I actually performed a test in a project with RN 0.18.1 and works like a charm :)

**Comment by httnn** [comment]
beautiful!

**Comment by httnn** [comment]
merged and published on npm, thanks for the PRs!

**Pull request merged**
