### PR TITLE
Use BackHandler instead BackAndroid

### LINKED ISSUE #24: BackAndroid was deprecated in 0.44
There is need to use `BackHandler` instead

### PR DESCRIPTION
**Pull request by farwayer**
fix #24 
Change is very simple but it should be included in major version bump

### CODE REVIEW

**Comment by xilonxiao** [comment]
Looking forward to this PR be merged.

**Review by cooperka — APPROVED** [review]

**Comment by cooperka** [comment]
For those wanting to use this fix in their app before @bodyflex has a chance to merge it, you can use [this fork](https://github.com/cribspot/react-native-simple-modal/releases/tag/2017-06-08-backHandler) that's based on latest master (v5.1.1). Simply put this in your `package.json` dependencies:

```json
"react-native-simple-modal": "https://github.com/cribspot/react-native-simple-modal.git#2017-06-08-backHandler"
```

**Comment by httnn** [comment]
sorry for the delay guys!

**Comment by httnn** [comment]
this has now been published as v6.0.0 @farwayer @xilonxiao @cooperka

**Pull request merged**
